name: Hetzner Online GmbH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Initialization environment
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install python3 python3-pip

      - name: Scaning
        run: |
          sudo python3 -m pip install -r requirements.txt
          sudo python3 ipcfscanner.py -f ipv4/Hetzner-Online-GmbH.txt -o Hetzner-Online-GmbH.txt
 
      - name: Upload Scan Result
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: Hetzner-Online-GmbH
          artifacts: "Hetzner-Online-GmbH.txt"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: release_body.txt
