name: Hetzner Online GmbH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Initialization environment
        run: |
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y install python3 python3-pip
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED

      - name: Scaning
        run: |
          sudo python3 ipcfscanner.py -f ipv4/Hetzner-Online-GmbH.txt -o Hetzner-Online-GmbH.txt
 
      - name: Upload Scan Result
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: Hetzner-Online-GmbH
          artifacts: "Hetzner-Online-GmbH.txt"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: release_body.txt
